[project]
name = "iris-gui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "elevate>=0.1.3",
    "requests>=2.32.4",
]
